---
title       : Writing and managing R packages
subtitle    : 13 Sep 2016, Melbourne Users of R Network (MelbURN)
author      : Damjan Vukcevic
job         : Statistician & data scientist
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      #
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
---

## What is an R package?

> "Packages are the fundamental units of reproducible R code." (Hadley Wickham)

---

## Why R packages?

- Easier management, re-use and sharing of code

- Helpful even just for yourself

* Saves time

    - Follow conventions, to avoid having to think about plumbing all the time
    - Quick, easier re-use
    - Quicker, easier, sharing

* Easy to create!  (...with a little help from Hadley)

---

> "I really should just make an R package with these functions so I don't have
to keep copy/pasting them like a goddamn luddite." (Hilary Parker)

> "R packages are the best way to distribute R code and documentation..." (Karl
Broman)

---

## `functions.R`, the poor man's R package

(Show example here...)

---

## Your first R package

Create folder structure

```
mypackage/
└── R/
```

---

## Your first R package

Move `functions.R` into the `R` subfolder

```
mypackage/
└── R/
    └── functions.R
```

---

## Your first R package

Create the `DESCRIPTION` and `NAMESPACE` files

```
mypackage/
├── R/
│   └── functions.R
├── DESCRIPTION
└── NAMESPACE
```

---

## Your first R package

Your `DESCRIPTION` file should look similar to:

```
...
```

---

## Your first R package

Your `NAMESPACE` file should look like:

```
# Export all names
exportPattern(".")
```

---

## Your first R package

Install your package:

```
R CMD INSTALL mypackage
```

(Run this on the command line, from the folder one level above `mypackage`)

---

## Your first R package

Use your new package in R:

```
library(mypackage)
dostuff(x)
```

---

## Benefits (package vs `functions.R`)

* Easier to re-use
* Easier to share
* Easier to maintain as complexity increases

    - Can split seamlessly into multiple files
    - Can version track separately
    - Can add extra stuff: documentation, tests,... (see later)

---

## Easy development with `devtools`

```
create()
```

---

## A package-based workflow

* Use `devtools`

* Main idea: during interactive development, use `load_all("mypackage")`
instead of `source("functions.R")`

---

## A package-based workflow

```
# Development
dev_mode()
setwd()  -- ?
load_all()
    Repeat!
```

---

## A package-based workflow

```
# Installation (dev mode)
document()
Update DESCRIPTION
check()
install()
```

---

## A package-based workflow

```
# Installation (normal mode)
undo dev_mode()
install()
```

---

## A package-based workflow

* Any personal tips?

---

## Documentation

(Need examples here...)

---

## Some important (advanced) concepts

* Namespaces (exporting)
* Dependencies
* Lazy loading

---

## Tips & tricks, other stuff

* Difference between `library()` and `require()`
* Invoke function from other packages using `package::function()`

---

## Levelling up

* Data & examples
* Vignettes
* Testing
* Sharing your package

---

## Data & examples

...

---

## Vignettes

...

---

## Testing

...

---

## Sharing your R package

* What to do before sharing
* Where to share
* How to share
* GitHub
* CRAN

---

## Managing R packages (yours or others)

* Installing packages
* Finding all dependencies and installing them
* Upgrading packages
* Upgrading all packages after a major R upgrade
* Viewing man pages for packages

---

## Installing packages

- Locally (e.g. your own)
- From CRAN
* `install.packages()` or `R CMD INSTALL` or `install_*` (`devtools`)
- From GitHub

---

## Finding all dependencies and installing them

- `reinstallr()`

---

## Upgrading packages

* `update.packages()`
* `reinstallr` package

---

## Upgrading all packages after a major R upgrade (CRAN packages only)

- `update.packages(checkBuilt=TRUE, ask=FALSE)`

---

## Viewing man pages for packages

...

---

## Tips for using RStudio and packages

* <https://support.rstudio.com/hc/en-us/sections/200130627-Package-Development>

---

## More info

* [Writing an R package from scratch][hilary], Hilary Parker
* [R packages][hadley], Hadley Wickham *(read this!)*
* [R package primer][broman], Karl Broman
* [Writing R Extensions][R-exts], R Core Team **(best to avoid...)**

[hilary]: https://hilaryparker.com/2014/04/29/writing-an-r-package-from-scratch/
[broman]: http://kbroman.org/pkg_primer/
[hadley]: http://r-pkgs.had.co.nz/
[R-exts]: https://cran.r-project.org/doc/manuals/r-release/R-exts.html

## Useful packages

* [devtools](https://github.com/hadley/devtools)
* [reinstallr](https://github.com/calligross/reinstallr)
* [installr](https://github.com/talgalili/installr/) (Windows only)
